name: todo_app
description: Simple Todo app.

publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  drift: ^2.19.1+1
  flutter_slidable: ^3.1.1
  path: ^1.8.2
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.19.1
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 400
        - asset: assets/fonts/DancingScript-Medium.ttf
          weight: 500
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700
